import AppKit
import Combine

/// Watches NSPasteboard.general by polling changeCount (the only supported
/// detection mechanism on macOS) and stores new items.
final class ClipboardMonitor {
    private let database: ClipDatabase
    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount = 0
    private var skipNextChange = false
    private var cancellables = Set<AnyCancellable>()

    var isPaused = false

    /// Pasteboard types that mean "do not record this". ConcealedType is the
    /// convention password managers (1Password, Bitwarden, ...) set on copied
    /// secrets; TransientType marks ephemeral writes.
    private static let skippedTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    init(database: ClipDatabase) {
        self.database = database
    }

    func start() {
        lastChangeCount = pasteboard.changeCount
        scheduleTimer()
        AppSettings.shared.$pollingIntervalMs
            .removeDuplicates()
            .dropFirst()
            .sink { [weak self] _ in self?.scheduleTimer() }
            .store(in: &cancellables)
    }

    /// Called right before Clippy writes the pasteboard itself, so its own
    /// paste does not get re-captured (keeps history order stable).
    func ignoreNextChange() {
        skipNextChange = true
    }

    private func scheduleTimer() {
        timer?.invalidate()
        let interval = max(0.05, AppSettings.shared.pollingIntervalMs / 1000.0)
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            self?.tick()
        }
        timer.tolerance = interval / 4
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func tick() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount
        if skipNextChange {
            skipNextChange = false
            return
        }
        guard !isPaused else { return }
        captureCurrentPasteboard()
    }

    private func captureCurrentPasteboard() {
        guard let types = pasteboard.types, !types.isEmpty else { return }
        guard Self.skippedTypes.isDisjoint(with: Set(types)) else { return }

        let frontApp = NSWorkspace.shared.frontmostApplication
        if let bundleID = frontApp?.bundleIdentifier,
           AppSettings.shared.ignoredBundleIDs.contains(bundleID) {
            return
        }

        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            captureText(text, from: frontApp)
            return
        }
        captureImageIfPresent(from: frontApp)
    }

    private func captureText(_ text: String, from frontApp: NSRunningApplication?) {
        let rtf = pasteboard.data(forType: .rtf)
        let html = pasteboard.data(forType: .html)
        let typeIdentifier: String
        if rtf != nil {
            typeIdentifier = "public.rtf"
        } else if html != nil {
            typeIdentifier = "public.html"
        } else {
            typeIdentifier = "public.utf8-plain-text"
        }

        var clip = Clip(
            id: nil,
            contentText: text,
            contentRTF: rtf,
            contentHTML: html,
            typeIdentifier: typeIdentifier,
            sourceAppBundleID: frontApp?.bundleIdentifier,
            sourceAppName: frontApp?.localizedName,
            createdAt: Date()
        )
        do {
            try database.saveCapturedClip(&clip)
        } catch {
            NSLog("Clippy: failed to save clip: \(error)")
        }
    }

    /// Images are captured only when the pasteboard carries no text: a copied
    /// picture, a screenshot, not a rich-text snippet that happens to embed one.
    private func captureImageIfPresent(from frontApp: NSRunningApplication?) {
        guard AppSettings.shared.captureImages,
              let pngData = Self.pngData(from: pasteboard)
        else { return }
        guard pngData.count <= AppSettings.shared.maxImageSizeMB * 1_048_576 else { return }

        do {
            let stored = try database.media.store(pngData: pngData)
            var clip = Clip(
                id: nil,
                contentText: "",
                contentRTF: nil,
                contentHTML: nil,
                typeIdentifier: "public.png",
                sourceAppBundleID: frontApp?.bundleIdentifier,
                sourceAppName: frontApp?.localizedName,
                createdAt: Date(),
                contentKind: .image,
                mediaFilename: stored.mediaFilename,
                thumbFilename: stored.thumbFilename,
                pixelWidth: stored.pixelWidth,
                pixelHeight: stored.pixelHeight,
                byteSize: stored.byteSize
            )
            try database.saveCapturedImageClip(&clip)
        } catch {
            NSLog("Clippy: failed to save image clip: \(error)")
        }
    }

    private static func pngData(from pasteboard: NSPasteboard) -> Data? {
        if let png = pasteboard.data(forType: .png) { return png }
        guard let tiff = pasteboard.data(forType: .tiff),
              let rep = NSBitmapImageRep(data: tiff)
        else { return nil }
        return rep.representation(using: .png, properties: [:])
    }
}
